export const accountActionTypes = {
  GET_ACCOUNT: 'GET_ACCOUNT',
  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',
  UPDATE_ORDER: 'UPDATE_ORDER',
};
